const User = require('../model/User')
const OTP = require('../model/OTP')
const otpGenerator = require('otp-generator');
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const mailSender = require('../utils/mailSender');
const Profile = require('../model/Profile')
const {passwordUpdated} = require('../mail/templates/passwordUpdated')
const {otpTemplate} = require('../mail/templates/emailVerificationTemplate')
require('dotenv').config();


exports.sendOTP = async (req, res) => {
  try {
    // Fetch email from request body
    const { email } = req.body;

    // Check if user already exists
    const checkUserPresent = await User.findOne({ email });

    if (checkUserPresent) {
      return res.status(400).json({
        success: false,
        message: "User already registered...",
      });
    }

    // Generate OTP
    let otp = otpGenerator.generate(6, {
      upperCaseAlphabets: false,
      lowerCaseAlphabets: false,
      specialChars: false,
    });

    // Ensure the OTP is unique
    let result = await OTP.findOne({ otp });

    while (result) {
      otp = otpGenerator.generate(6, {
        upperCaseAlphabets: false,
        lowerCaseAlphabets: false,
        specialChars: false,
      });
      result = await OTP.findOne({ otp });
    }

    // Create the OTP entry in the database
    const otpPayload = { email, otp };
    const otpBody = await OTP.create(otpPayload);
    console.log(otpBody);

    // Send OTP email
    const emailContent = otpTemplate(otp); // Use the otpTemplate function to generate the HTML email
    const mailOptions = await mailSender(
      email,  // Recipient's email
      `OTP for Course Registration `,
      emailContent,  // The HTML content generated by the otpTemplate function
    );

    // Send the email using the mailSender utility
    // await mailSender(mailOptions);

    // Return response successfully
    res.status(200).json({
      success: true,
      message: 'OTP Sent Successfully',
      otp, // You might not want to send the OTP in the response body, for security reasons
    });

  } catch (error) {
    console.log(error);
    return res.json({
      success: false,
      message: error.message,
    });
  }
};


//SignUp
exports.signUp = async(req, res) =>{
  try{
    //data fetch from req
    const {firstName, lastName, email,password,   
           confirmPassword, accountType, otp
    } = req.body;

    if(!firstName || !lastName || !email ||
      !password || !confirmPassword || !otp){
        return res.status(403).json({
          success: false,
          message: 'All Fields are required',
        })
      }

      
      if(password !== confirmPassword){
        return res.status(400).json({
          success: false,
          message: 'Password and ConfirmPassword does not match try again',
        })
      }

      //check user already exist or not
      const existingUser = await User.findOne({email});
      if(existingUser){
        return res.status(400).json({

          success: false,
          message: "User is already registered",
        });
      }

      //find the most recent OTP stored in DB
      //createdAt -1 = Sorting in this way ensures that the most recent document (based on createdAt) appears first in the results.
      //.limit(1) restricts the number of documents returned to just one, ensuring only the most recent document is fetched.
      
      const recentOTP = await OTP.findOne({email}).sort({createdAt: -1}).limit(1);
      console.log(recentOTP); 

      //validate OTP 
      if(recentOTP.length === 0){
        return res.status(400).json({
          success:false,
          message: 'OTP Not Found...',
        })
      } else if(otp !== recentOTP.otp){
       return res.status(400).json({
        success: false,
        message: 'Invalid OTP',
       })
      }

      //Hash Password
      const hashedPassword = await bcrypt.hash(password, 10);

      //Create the user
      let approved = "";
      approved === 'Instructor' ? (approved = false) : (approved = true);
      
      //Create the Additional profile details
      //Entry in DB
      const profileDetails = await Profile.create({
        gender: null,
        dateOfBirth: null,
        about: null,
        contactNumber: null,
      })

      const user = await User.create({
        firstName,
        lastName,
        email,
        password: hashedPassword,
        accountType,
        additionalDetails: profileDetails._id,
        image: `https://api.dicebear.com/5.x/initials/svg?seed=${firstName}${lastName}`,
      })

      return res.status(200).json({
        success: true,
        message: 'User is registered Successfully',
        user,
      })
  }catch(error){
    console.log(error)
    return res.status(500).json({
      success: false,
      messsage: "User can't Registered"
    })
  }
}


exports.login = async (req, res) =>{
   try{
    const {email, password} = req.body;

    //validation of data
    if(!email || !password){
      return res.status(403).json({
        success: false,
        message: 'All Fields are required, please try again',
      });
    }

    //user check exist or not
    //.populate() is a Mongoose method used to fetch and replace a referenced field with its actual data.
    const user = await User.findOne({email}).populate('additionalDetails');
    if(!user){
      return res.status(401).json({
         success: true,
        message: 'User is not registrered, Please Signup'
      })
    }

     //generate JWT, after password matching
     if(await bcrypt.compare(password, user.password)){
      const token = jwt.sign({
        email: user.email, id: user.id, accountType: user.accountType
      },
    process.env.JWT_SECRET,
    {
      expiresIn: "24h",
    }
    )
     
      user.token = token,
      user.password = undefined;

      //create cookies and send response
      const options ={
        expies: new Date(Date.now() + 3*24*60*60*1000), //expires time = 3 days
        httpOnly: true,
      }
      
      res.cookie('token', token, options).status(200).json({
        success: true, 
        token,
        user,
        message: 'Logged in Sucessfully',
      })
    }else{
      return res.status(401).json({
        success: false,
        message: 'Password is incorrect',
      })
    }
   }catch(error){
   console.log(error);
   return res.status(500).json({
    success: false,
    message: 'Login Failure, Please try again'
   })
   }
}

//homework given
exports.changePassword = async (req, res) => {
  try {
    // Get user data from req.user
    const userDetails = await User.findById(req.user.id)

    // Get old password, new password, and confirm new password from req.body
    const { oldPassword, newPassword } = req.body

    // Validate old password
    const isPasswordMatch = await bcrypt.compare(
      oldPassword,
      userDetails.password
    )
    if (!isPasswordMatch) {
      // If old password does not match, return a 401 (Unauthorized) error
      return res
        .status(401)
        .json({ success: false, message: "The password is incorrect" })
    }

    // Update password
    const encryptedPassword = await bcrypt.hash(newPassword, 10)
    const updatedUserDetails = await User.findByIdAndUpdate(
      req.user.id,
      { password: encryptedPassword },
      { new: true }
    )

    // Send notification email
    try {
      const emailResponse = await mailSender(
        updatedUserDetails.email,
        "Password for your account has been updated",
        passwordUpdated(
          updatedUserDetails.email,
          `Password updated successfully for ${updatedUserDetails.firstName} ${updatedUserDetails.lastName}`
        )
      )
      console.log("Email sent successfully:", emailResponse.response)
    } catch (error) {
      // If there's an error sending the email, log the error and return a 500 (Internal Server Error) error
      console.error("Error occurred while sending email:", error)
      return res.status(500).json({
        success: false,
        message: "Error occurred while sending email",
        error: error.message,
      })
    }

    // Return success response
    return res
      .status(200)
      .json({ success: true, message: "Password updated successfully" })
  } catch (error) {
    // If there's an error updating the password, log the error and return a 500 (Internal Server Error) error
    console.error("Error occurred while updating password:", error)
    return res.status(500).json({
      success: false,
      message: "Error occurred while updating password",
      error: error.message,
    })
  }
} 